import React from 'react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import { Target, TrendingUp, Sparkles } from 'lucide-react';

const data = [
  { name: 'Software Engineering', score: 91, color: '#8b5cf6' },
  { name: 'Programming', score: 87, color: '#06b6d4' },
  { name: 'Technology', score: 84, color: '#3b82f6' },
  { name: 'Developer Career', score: 76, color: '#6366f1' },
  { name: 'AI & ML', score: 68, color: '#10b981' },
  { name: 'Hardware', score: 61, color: '#f59e0b' },
  { name: 'Cybersecurity', score: 32, color: '#ef4444' },
  { name: 'Gaming', score: 25, color: '#64748b' }
];

export default function InterestProfileSection() {
  return (
    <section className="py-20 px-4 bg-[#07090e] border-b border-white/5 relative overflow-hidden">
      <div className="max-w-6xl mx-auto space-y-12">
        
        {/* Header */}
        <div className="text-center space-y-3 max-w-3xl mx-auto">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-500/10 border border-purple-500/30 text-purple-300 text-xs font-mono">
            <Target className="w-3.5 h-3.5 text-cyan-400" />
            <span>INTEREST SPECTRUM ANALYSIS</span>
          </div>
          <h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight">
            Student Interest Profile Spectrum
          </h2>
          <p className="text-slate-400 text-sm sm:text-base">
            Quantitative weight distribution inferred across all 8 Reel interactions.
          </p>
        </div>

        {/* Chart & Stats Container */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-center max-w-6xl mx-auto">
          
          {/* Main Chart */}
          <div className="lg:col-span-2 p-6 sm:p-8 rounded-3xl glass-panel border border-white/10 shadow-2xl space-y-4">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <h3 className="text-base font-bold text-white font-mono flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-cyan-400" /> INTEREST WEIGHT SCORE (%)
              </h3>
              <span className="text-xs text-slate-400 font-mono">AUTO-GENERATED BY AI</span>
            </div>

            <div className="h-[360px] w-full pt-4">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={data} layout="vertical" margin={{ top: 5, right: 30, left: 40, bottom: 5 }}>
                  <XAxis type="number" domain={[0, 100]} stroke="#64748b" tick={{ fill: '#94a3b8', fontSize: 12 }} />
                  <YAxis dataKey="name" type="category" stroke="#64748b" tick={{ fill: '#e2e8f0', fontSize: 12 }} width={140} />
                  <Tooltip
                    contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', borderRadius: '12px', color: '#fff' }}
                    formatter={(value) => [`${value}% Match`, 'Weight']}
                  />
                  <Bar dataKey="score" radius={[0, 8, 8, 0]}>
                    {data.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Core Insights Column */}
          <div className="space-y-4">
            <div className="p-6 rounded-2xl glass-panel-glow border border-purple-500/40 space-y-3">
              <div className="flex items-center justify-between text-xs font-mono text-purple-400 font-bold">
                <span>PRIMARY INFERRED CLUSTER</span>
                <Sparkles className="w-4 h-4 text-cyan-400" />
              </div>
              <h4 className="text-2xl font-extrabold text-white font-mono">Software Engineering</h4>
              <div className="text-4xl font-black text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-cyan-400 font-mono">
                91%
              </div>
              <p className="text-xs text-slate-300 leading-relaxed">
                Strongest affinity detected across low-level language internals, algorithmic efficiency, and scalable backend architecture.
              </p>
            </div>

            <div className="p-6 rounded-2xl glass-panel border border-white/5 space-y-3">
              <div className="flex items-center justify-between text-xs font-mono text-cyan-400 font-bold">
                <span>SECONDARY INTEREST</span>
              </div>
              <h4 className="text-xl font-bold text-white">Programming & Code Quality</h4>
              <div className="text-2xl font-bold text-cyan-400 font-mono">87%</div>
              <p className="text-xs text-slate-400">
                Driven by high completion rates on clean code practices and LeetCode problem solving.
              </p>
            </div>
          </div>

        </div>

      </div>
    </section>
  );
}
